[[language]]
name = "nix"
formatter = { command = "nixfmt" }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
formatter = { command = "sh", args = [
  "-c",
  "ruff format - | ruff check --select I --fix - ",
] }
auto-format = true

[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["-i", "2", "-"] }
auto-format = true

[[language]]
name = "typst"
auto-format = true

[language-server.tinymist.config]
tinymist.formatterMode = "typstyle"

[language-server.yaml-language-server.config.yaml.format]
enable = true

[language-server.yaml-language-server.config.yaml.schemas]
kubernetes = "/*.yaml"
"https://json.schemastore.org/github-action.json" = "/.github/**/actions.yml"
"https://json.schemastore.org/github-workflow.json" = "/.github/workflows/*.{yml,yaml}"

[language-server.yaml-language-server.config.yaml.schemaStore]
url = "https://json.schemastore.org/package.json"
