[[language]]
name = "nix"
formatter = { command = "nixfmt" }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "python"
# language-servers = ["pylsp", "ruff"]
language-servers = ["pyrefly", "ruff"]
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["-i", "2", "-"] }
auto-format = true

[[language]]
name = "typst"
soft-wrap.wrap-at-text-width = true
language-servers = ["tinymist", "harper-ls"]
auto-format = true

[[language]]
name = "markdown"
soft-wrap.wrap-at-text-width = true

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.tinymist.config]
tinymist.formatterMode = "typstyle"
tinymist.lint.enabled = true

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls]
diagnosticSeverity = "warning"
isolateEnglish = false
dialect = "American"
maxFileLength = 12000
ignoredLintsPath = []

[language-server.harper-ls.config.harper-ls.linters]
SpellCheck = true
SpelledNumbers = false
AnA = true
SentenceCapitalization = true
UnclosedQuotes = true
WrongQuotes = false
LongSentences = true
RepeatedWords = true
Spaces = true
Matcher = true
CorrectNumberSuffix = true

[language-server.harper-ls.config.harper-ls.codeActions]
ForceStable = false

[language-server.harper-ls.config.harper-ls.markdown]
IgnoreLinkTitle = false

[language-server.yaml-language-server.config.yaml.format]
enable = true

[language-server.yaml-language-server.config.yaml.schemas]
kubernetes = "/*.yaml"
"https://json.schemastore.org/github-action.json" = "/.github/**/actions.yml"
"https://json.schemastore.org/github-workflow.json" = "/.github/workflows/*.{yml,yaml}"

[language-server.yaml-language-server.config.yaml.schemaStore]
url = "https://json.schemastore.org/package.json"
